INSERT INTO ROL(ROL_TITULO,ROL_DESCRIPCION) VALUES('Administrador','Rol administrador');
INSERT INTO ROL(ROL_TITULO,ROL_DESCRIPCION) VALUES('Usuario','Rol usuario');

INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('Github');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('Facebook');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('Twitter');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('Twitch');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('Youtube');

INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Frontend');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Backend');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('DevOps');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Videogame Developer');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('UI/UX');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Database Developer');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Cloud Computing');

INSERT INTO LENGUAJE(NOMBRE_LENGUAJE) VALUES('Python');
INSERT INTO LENGUAJE(NOMBRE_LENGUAJE) VALUES('Javascript');
INSERT INTO LENGUAJE(NOMBRE_LENGUAJE) VALUES('Rust');
INSERT INTO LENGUAJE(NOMBRE_LENGUAJE) VALUES('Typescript');
INSERT INTO LENGUAJE(NOMBRE_LENGUAJE) VALUES('Java');
INSERT INTO LENGUAJE(NOMBRE_LENGUAJE) VALUES('Go');
INSERT INTO LENGUAJE(NOMBRE_LENGUAJE) VALUES('Ruby');

INSERT INTO PAIS(NOMBRE_PAIS) VALUES('Perú');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('México');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('Ecuador');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('Bolivia');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('Colombia');