INSERT INTO ROL(ROL_TITULO,ROL_DESCRIPCION) VALUES('ADMINISTRADOR','ROL ADMINISTRADOR');
INSERT INTO ROL(ROL_TITULO,ROL_DESCRIPCION) VALUES('USUARIO','ROL USUARIO');

INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('GITHUB');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('FACEBOOK');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('TWITTER');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('TWITCH');
INSERT INTO RED_SOCIAL(NOMBRE_RED_SOCIAL) VALUES('YOUTUBE');

INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Frontend');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Backend');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('DevOps');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Videogame Developer');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('UI/UX');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Database Developer');
INSERT INTO CONOCIMIENTO(NOMBRE_CONOCIMIENTO) VALUES('Cloud Computing');


INSERT INTO PAIS(NOMBRE_PAIS) VALUES('PERÚ');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('MÉXICO');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('ECUADOR');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('BOLIVIA');
INSERT INTO PAIS(NOMBRE_PAIS) VALUES('COLOMBIA');